### PR TITLE
Update manual CSV generation instructions

### LINKED ISSUE #3: The "Mobile (Including Tablet)" Dimension is Deprecated in GA
There is a good chance that this issue belongs in the upstream [browserslist/browserslist-ga
](https://github.com/browserslist/browserslist-ga) repo; if that is in fact the case I'll close this and open a new issue there.

That said, it appears the "Mobile (Including Tablet)" dimension required in the exported report is deprecated as indicated by the warning icon in the UI:

Screen shot of GA deprecation icon

As well as a warning prompt on save that reads:

>The following dimensions are deprecated:
>Mobile (Including Tablet)
>Deprecated concepts will eventually be removed, which may invalidate your report. Do you want to proceed?

Screen shot of GA Depreciation Modal

Unfortunately I am not familiar with the GA API myself and as a result had trouble finding more information about this depreciation so I don't have a suggested path forward. Regardless I thought it's worth it to start the discussion.

### PR DESCRIPTION
**Pull request by ogonkov**
Since browserslist/browserslist-ga#30 new dimension should be used.

Somehow fix #3

### CODE REVIEW

**Comment by galvarez421** [comment]
Hi @ogonkov, thank you for your contribution. I do not see "Device Type" as a dimension, but I do see "Device Category". Can you confirm that you see "Device Type" in your Google Analytics UI? This may be similar to https://github.com/browserslist/browserslist-ga-export/pull/5, in which the user language settings will play a role in what we should include in the instructions.

**Comment by ogonkov** [comment]
Sorry, I use GA on russian, you probably right

**Comment by ogonkov** [comment]
Yep, you right
Снимок экрана 2020-02-17 в 22 39 57

**Comment by galvarez421** [comment]
@ogonkov Thank you for your contribution. The updated dimension has been included in the updated README on the `develop` branch as part of https://github.com/browserslist/browserslist-ga-export/commit/4eaecbdced38b88b1653a911658e62fd67942190.

I am planning to document contribution guidelines. For now, I would recommend opening future pull requests on the `develop` branch so that the `master` branch can be reserved for merging in release-ready changes.

**Pull request closed without merging**
